SERVER:
  NAME: DTALK_SEND_PAS
  VERSION: 1.0.0
  DEBUG: True
  IS_TEST: True

# dingTalk openApi config
DINGTALK:
  BASE_URL: https://oapi.dingtalk.com/
  TOKEN_URL: gettoken

# dingTalk robot config information
ROBOT:
  APPKEY: dingsxsbv4swnn17bf3d
  APPSECRET: bn48xUE0feFcA0S9L2QS3TA7Gqp9J2-yrZR0baOQyxoY-aQI9rhLYetQDiZ0oWgj

# log base config, contain folder、 level、 format、 filename prefix
LOG:
  LOG_DIR: log
  LOG_LEVEL: debug
  LOG_FORMATTER: '%(asctime)s - %(pathname)s[line:%(lineno)d] - %(levelname)s - %(message)s'
  LOG_FILENAME_PREFIX: dtalk_send_pas

# Excel Template base config
# Please to check README.md configuration details
TEMPLATE:
  FILE: DingTalk_Bank_Salary.xls
  IS_TITLE: True
  SHEET_INDEX: 1
  COL_INDEX_DINGTALK_ID: 1
  COL_INDEX_HYLB: 2

# DingTalk no send message user list configuration, demo：['032511245938821831']
MANAGE:
  IS_ADD_IMAGE: http://pygo2.top/images/tw.png
  CONTROL: ['032511245938821831']

# DingTalk message content configuration,
# accord to the customized content information to push message by the HYLB(Case sensitive)
MESSAGE_COL:
  E01: [3, 4, 5, 6, 7, 8, 9, 28, 31, 26]
  E02: [3, 5, 6, 7, 8, 10, 11, 12, 13, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26]
