SERVER:
  NAME: DTALK_SEND_PAS
  VERSION: v1.0.1
  DEBUG: True
  IS_TEST: True

# developer parameters
DEV:
  DK_INTERVAL: 1.2

# dingTalk openApi url config
DINGTALK:
  BASE_URL: https://oapi.dingtalk.com/
  TOKEN_URL: gettoken

# dingTalk robot config information
ROBOT:
  APPKEY: dingsxsbv4swnn17bf3d
  APPSECRET: bn48xUE0feFcA0S9L2QS3TA7Gqp9J2-yrZR0baOQyxoY-aQI9rhLYetQDiZ0oWgj

# log base config, contain folder、 level、 format、 filename prefix
LOG:
  LOG_DIR: log
  LOG_LEVEL: debug
  LOG_FORMATTER: '%(asctime)s - %(pathname)s[line:%(lineno)d] - %(levelname)s - %(message)s'
  LOG_FILENAME_PREFIX: dtalk_send_pas

# Excel Template base config
# Please to check README.md configuration details
TEMPLATE:
  FILE: DingTalk_Bank_Salary.xls
  IS_TITLE: True
  SHEET_INDEX: 1
  COL_INDEX_DINGTALK_ID: 1
  COL_INDEX_HYLB: 2

# DingTalk no send message user list configuration, demo：['032511245938821831']
# default value is null, image reference url: http://pygo2.top/images/tw.png
MANAGE:
  TITLE: 2021-12月绩基本资明细
  IS_ADD_IMAGE:
  CONTROL: ['032511245938821831']

# DingTalk message content configuration,
# accord to the customized content information to push message by the HYLB(Case sensitive)
MESSAGE_COL:
  E01: [3, 5, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29]
  E02: [3, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 29]
  E03: [3, 6, 7, 8, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29]
  W01: [7, 11, 12, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33, 34, 35]
  W02: [7, 11, 12, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]
  B01: [7, 13, 14, 15, 16, 17, 21, 26, 28, 29, 30, 31, 32, 33, 34, 35]
  T01: [7, 11, 12, 13, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 28, 29, 30, 31, 32, 33, 34, 35]
  L01: [7, 11, 28, 29, 30, 31, 32, 33, 34, 35]
  Q01: [4, 6, 7, 8, 9, 12, 17, 20, 23, 25, 27]
  TEST: [3, 4, 5, 6, 7, 8, 9, 28, 31, 26]
